# Generated by Django 4.0.7 on 2022-09-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['language', '-modified'], 'verbose_name': 'CMS - About', 'verbose_name_plural': 'CMS - About'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['language', '-modified'], 'verbose_name': 'CMS - Home', 'verbose_name_plural': 'CMS - Home'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['language', '-priority_order'], 'verbose_name': 'CMS - Project', 'verbose_name_plural': 'CMS - Projects'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['language', '-priority_order'], 'verbose_name': 'CMS - Technology', 'verbose_name_plural': 'CMS - Technologies'},
        ),
        migrations.AddField(
            model_name='about',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=30, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='home',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=30, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=30, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='technology',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=30, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
    ]
