# Generated by Django 4.0.7 on 2022-09-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_about_options_alter_home_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeentry',
            options={'ordering': ['-priority_order'], 'verbose_name': 'Resume entry', 'verbose_name_plural': 'Resume entries'},
        ),
        migrations.AddField(
            model_name='resumeentry',
            name='priority_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Positive number used to order, the highest number is positioned first.', verbose_name='Priority order'),
        ),
    ]
