# Generated by Django 4.0.7 on 2022-12-15 13:54

import apps.core.utils
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('core', '0004_service'), ('core', '0005_home_contact_msg_project_activate_details_and_more'), ('core', '0006_alter_about_body_alter_home_card_body_and_more')]

    dependencies = [
        ('core', '0003_alter_resumeentry_options_resumeentry_priority_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('fa_icon', models.CharField(max_length=30, verbose_name='Fontawesome icon')),
                ('title', models.CharField(max_length=255, verbose_name='Service title')),
                ('description', models.TextField(verbose_name='Service description')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.home')),
            ],
            options={
                'verbose_name': 'CMS - Service',
                'verbose_name_plural': 'CMS - Services',
                'ordering': ['home', 'title'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='activate_details',
            field=models.BooleanField(default=True, help_text='Activate project details button and expose project details page', verbose_name='Activate project details'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to project code repository. leave this field blank to hide the corresponding button on the projects page.', null=True, verbose_name='Github repository URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='Link to deployed project. Leave this field blank to hide the corresponding button on the projects page.', null=True, verbose_name='Website URL or link to project demo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image_webp',
            field=models.ImageField(blank=True, editable=False, help_text='Auto-generated WEBP version of [Cover image].', null=True, upload_to=apps.core.utils.upload_cms_image_location, verbose_name='Cover image (Webp)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Project summary to display in project list.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=tinymce.models.HTMLField(help_text="Long description about the project, it's the content of the project details page.", verbose_name='Project details'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Url endpoint for this project, leave blank to auto-generate.', max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(help_text='< Accept HTML >', verbose_name='Profile body'),
        ),
        migrations.AlterField(
            model_name='home',
            name='card_body',
            field=models.TextField(blank=True, help_text='< Accept HTML >', verbose_name='Card Body'),
        ),
        migrations.AlterField(
            model_name='home',
            name='card_title',
            field=models.TextField(blank=True, help_text='< Accept HTML >', verbose_name='Card title'),
        ),
        migrations.AddField(
            model_name='home',
            name='contact_msg',
            field=models.TextField(blank=True, help_text='< Accept HTML >', null=True, verbose_name='Invitation to contact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='< Accept HTML > Project summary to display in project list.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=tinymce.models.HTMLField(help_text="< Accept HTML > Long description about the project, it's the content of the project details page.", verbose_name='Project details'),
        ),
        migrations.AlterField(
            model_name='resumeentry',
            name='description',
            field=models.TextField(blank=True, help_text='< Accept HTML >', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, help_text='< Accept HTML >', verbose_name='Description'),
        ),
    ]
