# Generated by Django 4.0.7 on 2022-12-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_squashed_0006_alter_about_body_alter_home_card_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-priority_order', 'home', 'title'], 'verbose_name': 'CMS - Service', 'verbose_name_plural': 'CMS - Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='priority_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Positive number used to order, the highest number is positioned first.', verbose_name='Priority order'),
        ),
    ]
