# Generated by Django 4.0.7 on 2022-12-22 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_service_options_service_priority_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeentry',
            options={'ordering': ['-type', '-priority_order'], 'verbose_name': 'Resume entry', 'verbose_name_plural': 'Resume entries'},
        ),
        migrations.AddField(
            model_name='resumeentry',
            name='project',
            field=models.OneToOneField(blank=True, help_text='Related project to link technologies and details (Can be null).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
    ]
