# Generated by Django 4.0.7 on 2022-12-26 23:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_resumeentry_options_resumeentry_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, help_text="< Accept HTML > Long description about the project, it's the content of the project details page.", null=True, verbose_name='Project details'),
        ),
    ]
