# Generated by Django 4.0.9 on 2023-02-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_project_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['-priority_order'], 'verbose_name': 'CMS - Technology', 'verbose_name_plural': 'CMS - Technologies'},
        ),
        migrations.RemoveField(
            model_name='technology',
            name='description',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='language',
        ),
        migrations.CreateModel(
            name='TechnologyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=30, verbose_name='Language')),
                ('description', models.TextField(blank=True, help_text='< Accept HTML > Technology description to display on the "About" page', null=True, verbose_name='Description')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technology')),
            ],
            options={
                'verbose_name': 'CMS - Technology Description',
                'verbose_name_plural': 'CMS - Technology Descriptions',
                'ordering': ['language'],
            },
        ),
    ]
