# Generated by Django 4.0.9 on 2023-02-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_technology_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['slug', 'language', '-priority_order'], 'verbose_name': 'CMS - Project', 'verbose_name_plural': 'CMS - Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Url endpoint for this project, leave blank to auto-generate. <br><strong>WARNING:</strong> Set the same slug for the project model in different languages.', max_length=255, verbose_name='Slug'),
        ),
    ]
