# Generated by Django 4.1.6 on 2023-02-22 15:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_project_options_alter_project_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="base",
            name="color_four",
            field=colorfield.fields.ColorField(
                default="#6427ff",
                image_field=None,
                max_length=18,
                samples=[
                    ("#00d3ef", "sky"),
                    ("#6eb8f4", "blue"),
                    ("#3849ff", "indigo"),
                    ("#6427ff", "purple"),
                ],
                verbose_name="Background Color Four",
            ),
        ),
        migrations.AddField(
            model_name="base",
            name="color_one",
            field=colorfield.fields.ColorField(
                default="#00d3ef",
                image_field=None,
                max_length=18,
                samples=[
                    ("#00d3ef", "sky"),
                    ("#6eb8f4", "blue"),
                    ("#3849ff", "indigo"),
                    ("#6427ff", "purple"),
                ],
                verbose_name="Background Color One",
            ),
        ),
        migrations.AddField(
            model_name="base",
            name="color_three",
            field=colorfield.fields.ColorField(
                default="#3849ff",
                image_field=None,
                max_length=18,
                samples=[
                    ("#00d3ef", "sky"),
                    ("#6eb8f4", "blue"),
                    ("#3849ff", "indigo"),
                    ("#6427ff", "purple"),
                ],
                verbose_name="Background Color Three",
            ),
        ),
        migrations.AddField(
            model_name="base",
            name="color_two",
            field=colorfield.fields.ColorField(
                default="#6eb8f4",
                image_field=None,
                max_length=18,
                samples=[
                    ("#00d3ef", "sky"),
                    ("#6eb8f4", "blue"),
                    ("#3849ff", "indigo"),
                    ("#6427ff", "purple"),
                ],
                verbose_name="Background Color Two",
            ),
        ),
    ]
