# Generated by Django 4.0.5 on 2022-08-24 03:28

import apps.website.utils
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.website.utils.upload_cms_image_location, verbose_name='Profile image')),
                ('body', models.TextField(verbose_name='Profile body')),
                ('activate_stack', models.BooleanField(default=True, verbose_name='Activate stack section')),
                ('activate_trust_me', models.BooleanField(default=True, verbose_name='Activate trust me section')),
                ('activate_resume', models.BooleanField(default=True, verbose_name='Activate resume section')),
            ],
            options={
                'verbose_name': 'CMS - About',
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('email', models.EmailField(help_text='Contact email', max_length=255, verbose_name='Email')),
                ('brand', models.CharField(help_text='Name of your personal brand', max_length=255, verbose_name='Brand')),
                ('logo', models.ImageField(help_text='Logo of your personal brand', upload_to=apps.website.utils.upload_cms_image_location, verbose_name='Logo')),
                ('favicon', models.ImageField(help_text='Favicon of the website', upload_to=apps.website.utils.upload_cms_image_location, verbose_name='favicon')),
                ('github', models.URLField(help_text='Example: https://github.com/dev-user', verbose_name='Github profile url')),
                ('linkedin', models.URLField(help_text='Example: https://www.linkedin.com/in/dev-user', verbose_name='Linkedin profile url')),
            ],
            options={
                'verbose_name': 'CMS - Base',
                'verbose_name_plural': 'CMS - Base',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('card_title', models.TextField(blank=True, verbose_name='Card title')),
                ('card_body', models.TextField(blank=True, verbose_name='Card Body')),
                ('dev_photo', models.ImageField(blank=True, null=True, upload_to=apps.website.utils.upload_cms_image_location, verbose_name='Developer photo')),
            ],
            options={
                'verbose_name': 'CMS - Home',
                'verbose_name_plural': 'CMS - Home',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('cover_image', models.ImageField(upload_to=apps.website.utils.upload_cms_image_location, verbose_name='Cover image')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(blank=True, help_text='Url endpoint of this project, leave blank to auto-generate.', max_length=255, unique=True, verbose_name='Slug')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(help_text='Long description about the project, it is the content of the project endpoint', verbose_name='Project details')),
            ],
            options={
                'verbose_name': 'CMS - Project',
                'verbose_name_plural': 'CMS - Projects',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.website.utils.upload_cms_image_location, verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority_order', models.PositiveSmallIntegerField(default=0, help_text='Positive number used to order, the highest number is positioned first.', verbose_name='Priority order')),
                ('about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.about')),
                ('project_entry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.project')),
            ],
            options={
                'verbose_name': 'CMS - Technology',
                'verbose_name_plural': 'CMS - Technologies',
                'ordering': ['priority_order'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('start', models.DateField(verbose_name='Start date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('Experience', 'Experience'), ('Education', 'Education')], default='Experience', max_length=10, verbose_name='Type of entry')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.about')),
            ],
            options={
                'verbose_name': 'Resume entry',
                'verbose_name_plural': 'Resume entries',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.website.utils.upload_cms_image_location, verbose_name='Logo')),
                ('priority_order', models.PositiveSmallIntegerField(default=0, help_text='Positive number used to order, the highest number is positioned first.', verbose_name='Priority order')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.about')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
