# Generated by Django 4.0.5 on 2022-08-25 12:42

import apps.website.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='logo',
            field=models.FileField(help_text='Logo of your personal brand. Allow image files (JPG, PNG, GIF, WEBP) + svg files', upload_to=apps.website.utils.upload_cms_image_location, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg'])], verbose_name='Logo'),
        ),
    ]
